### PR TITLE
ported changes from globalscaletechnologies for EspressoBin

### PR DESCRIPTION
**Pull request by heaterC**
These changes ported from [Globalscaletechnologies](https://github.com/globalscaletechnologies/mv-ddr-marvell/tree/mv_ddr-armada-18.12-gti) seem to be vital for EspressoBin v7 DDR4 1GB 1cs.

### CODE REVIEW

**Comment by pali** [comment]
Hello! Development branch is [mv-ddr-devel](https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/tree/mv-ddr-devel). Could you rebase it on top of this branch? [mv_ddr-armada-18.12](https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/commits/mv_ddr-armada-18.12) is old and is not updated since 22 Nov 2018.

**Comment by heaterC** [comment]
Ok. They both didn't look recent to me! ;-)

**Comment by pali** [comment]
mv-ddr-devel was updated in Jun 25, 2020, which is recent :-)

**Comment by heaterC** [comment]
I had a look at the changes from Globalscale and they seem to interfere with changes from 18.12 to devel. Unfortunately, I lack the knowledge to merge the correct changes into the devel branch.

I already asked the guys at Globalscale to PR their changes at the Marvell repo but did not get a reply so far.

I am sorry I am no help at this point, since I am not an embedded developer and can only fulfill organisational tasks.

**Comment by pali** [comment]
So pickup changes manually from their repo, same changes which you did for branch old mv_ddr-armada-18.12.

**Comment by pali** [comment]
@heaterC: Could you please just cherry-pick changes which are needed for DDR4 1GB 1cs and rebase them on top of mv-ddr-devel branch?

**Comment by heaterC** [comment]
I am sorry I will try as soon as I can find some time. :-(

**Comment by pali** [comment]
also do not forget to change base branch of this pull request to `mv-ddr-devel` via **Edit** button near pull request title.

**Comment by heaterC** [comment]
These patches seem all to be applied already in branch mv-ddr-marvell.

**Comment by pali** [comment]
Are there really all patches? If yes, then you do not have to do anything else :-)

**Pull request closed without merging**
