### PR TITLE
Odt read fix

### PR DESCRIPTION
**Pull request by cpackham**

### CODE REVIEW

**Comment by pali** [comment]
@cpackham @Derek0425: Seems that this change was merged only to old [mv_ddr-armada-18.09](https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/tree/mv_ddr-armada-18.09) branch and not into the last [mv-ddr-devel](https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell/tree/mv-ddr-devel) branch.

Can you merge it also into mv-ddr-devel?

**Comment by pali** [comment]
CC @kostapr; see my previous comment in this pull request. Can you look at it and possibly merge it also into mv-ddr-devel branch?

**Comment by kostapr** [comment]
Added to mv-ddr-devel - #5a6f516cbf1d8592409f91f9ee2a3e902c64bde0 and #a43811b1ea6fce8beb59bea9f2d6f70d66e70880

**Comment by pali** [comment]
Thank you!

**Pull request merged**
